#!/usr/bin/env python3
"""Regenerate local preview files by stitching header.html + <page>.html +
footer.html together for each page listed in PAGES below.

These preview files are LOCAL-ONLY — they are not part of the Squarespace
deployment. Live, header.html and footer.html get pasted into Squarespace's
Header/Footer Code Injection fields separately, and each page's body content
gets pasted into that page's own code block. This script exists purely so
changes can be eyeballed in an ordinary browser before copying anything into
Squarespace.

Run after editing header.html, footer.html, or any page file:
    python3 build-preview.py
"""
import re
import pathlib

root = pathlib.Path(__file__).parent

# source page -> generated preview file
PAGES = {
    "index.html": "test.html",
    "about.html": "test-about.html",
    "404.html": "test-404.html",
}


def build_preview(page_name: str, output_name: str, header: str, footer: str) -> None:
    page = (root / page_name).read_text()
    page_head_inner = re.search(r"<head>(.*?)</head>", page, re.S).group(1)
    page_body_inner = re.search(r"<body>(.*?)</body>", page, re.S).group(1)

    combined = f"""<!--
    AUTO-GENERATED by build-preview.py from header.html + {page_name} + footer.html.
    Don't hand-edit this file — edits get overwritten the next time the script
    runs. Make changes in those three files instead, then re-run:
        python3 build-preview.py
-->
<!DOCTYPE html>
<html lang="en">
<head>
{page_head_inner}
{header}
</head>
<body>
{page_body_inner}
{footer}
</body>
</html>
"""
    (root / output_name).write_text(combined)
    print(f"{output_name} regenerated from header.html + {page_name} + footer.html")


def main() -> None:
    header = (root / "header.html").read_text()
    footer = (root / "footer.html").read_text()
    for page_name, output_name in PAGES.items():
        build_preview(page_name, output_name, header, footer)


if __name__ == "__main__":
    main()
